name: Setup Grafana with Helm on AWS

on:
  push:
    branches:
      - main

jobs:

  deploy:
    name: Deploy Grafana
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Update kubeconfig
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name ${{ secrets.KUBERNETES_CLUSTER_NAME }}

      - name: Add stable Helm repository
        run: |
          helm repo add stable https://charts.helm.sh/stable

      - name: Helm version
        run: |
          helm version

      - name: Helm repo update
        run: |
          helm repo update

      - name: Helm repo add grafana
        run: |
          helm repo add grafana https://grafana.github.io/helm-charts
          helm repo update

      - name: Get Kubernetes Context
        run: kubectl config get-contexts

      - name: Install Grafana
        working-directory: src
        shell: bash
        run: |
          chmod +x *.sh
          ./grafana.sh